config/routes.rb
Rails.application.routes.draw do
 get 'monstruos/index'

  get 'monstruos/show'

  resources :tweets
  resources :monstruos do
    collection do
      get 'ver'
    end
  end
  
  root 'tweets#default'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monstruo.rb
class Monstruo < ActiveRecord::Base
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :monstruo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  
  def index
  end

  def show
  end
  
  def ver    
  end
  
  def destroy
    monstruo = Monstruo.find(params[:id])
    monstruo.destroy
    redirect_to monstruos_path
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def default
  end
  
  def index
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
                 
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "logo" %>
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>

    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Critter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container"> 
      <%= yield %>
    <end>
  </body>
</html>

app/views/monstruos/index.html.erb
<!------------------------------------------------------ 
Acá va a ir el listado de monstruos usando los tags  
<ul> y <li>.
Debe tener un título y mostrar el nombre (en negrita) y
la descripción.
------------------------------------------------------>

HACER <br>
/app/views/monstruos/index.html.erb

app/views/monstruos/show.html.erb
Ver un monstruo <br>
/app/views/monstruos/show.html.erb

app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

app/views/tweets/default.html.erb
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  
  <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>
  <li> <%= link_to "Ver el primer monstruo", ver_monstruos_path %></li>
  
</ul>

app/views/tweets/index.html.erb
<!-- Listado de tweets -->

app/views/tweets/show.html.erb
<!-- Ver un tweet -->